name: Deploy Toolbar Reference Page

on:
  pull_request:
    branches: ["main"]
    types:
      - labeled
      - synchronize

jobs:
  deploy-reference-page:
    if: contains(github.event.pull_request.labels.*.name, 'Toolbar')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 22.4

      - name: Install dependencies
        working-directory: /toolbar-app
        run: |
          node -v
          npm -v
          npm install

      - name: Run build
        working-directory: /toolbar-app
        run: |
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "/toolbar-app/dist"
          publish_branch: gh_pages
          destination_dir: "/toolbar-app/"

      - name: Leave comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Your Tutorial Preview has been deployed: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/toolbar-app/'
            });
